### ISSUE TITLE
[BUG] error in radial commands

### ISSUE THREAD

**Issue by MrNewb** [Qbox-project/qbx_radialmenu#17]
### Summary

Possible issue in /hat and other /commands

### Reproduction

/hat command and a few others are giving a client side error, radial menu buttons are fixed from the recent update but these errors are happening. I am using qb-core with some cherry picked qbox so im open to there being some breaking changes on compatibility but I believe it may be an overlooked error
![errrr](https://user-images.githubusercontent.com/47620135/234482038-bef02963-d6c8-44dd-a9c7-bf1236395acf.png)

### Expected behavior

to remove the clothing

### Actual behavior

errrrrr

### Last Updated

today

### Custom Resources

meh

### Resource Rename

qb-radialmenu

**Comment by TonybynMp4** [comment]
i definitely overlooked this ngl
