### ISSUE TITLE
Does not open with and key binds

### ISSUE THREAD

**Issue by StabbyMcGhost** [Qbox-project/qbx_radialmenu#23]
### Summary

Does not open with and key binds

### Reproduction

it starts with no errors and no errors in F8. I press and hold F1 and have tried every key on my keyboard it just stopped working today. Fresh server only added spooner 2 days ago and it was working after I added spooner.

### Expected behavior

To work

### Actual behavior

No work

### Last Updated

Today see if it would fix it.

### Custom Resources

spooner

### Resource Rename

no

**Comment by TonybynMp4** [comment]
It uses the ox_lib radial menu keybind.

**Comment by DevX32** [comment]
> ### Summary
> Does not open with and key binds
> 
> ### Reproduction
> it starts with no errors and no errors in F8. I press and hold F1 and have tried every key on my keyboard it just stopped working today. Fresh server only added spooner 2 days ago and it was working after I added spooner.
> 
> ### Expected behavior
> To work
> 
> ### Actual behavior
> No work
> 
> ### Additional context
> _No response_
> 
> ### Last Updated
> Today see if it would fix it.
> 
> ### Custom Resources
> spooner
> 
> ### Resource Rename
> no

bcz the default keybind is z not f1

**Comment by yxcinebendjebbar** [comment]
> bcz the default keybind is z not f1

i have tried changing it to f1 but its not working?

``` lua
lib.addKeybind({
    name = 'ox_lib-radial',
    description = locale('open_radial_menu'),
    defaultKey = 'F1',
.
.
.
```
