### ISSUE TITLE
Being able to use radial menu while being down or dead

### ISSUE THREAD

**Issue by KostaZx** [Qbox-project/qbx_radialmenu#47]
### Summary

You can use the radial menu while down or dead

### Reproduction

1. /kill me
2. Pressing F1 opens the radial menu, which is the same as when the player is alive.

### Expected behavior

Not being able to use radial menu while being down/dead.

### Actual behavior

I can use radial menu while being down/dead.

### Additional context

-

### Current Version

v0.1.0

### Custom Resources

-

**Comment by TonybynMp4** [comment]
It shouldn't happen, are you using qbx_medical?

**Comment by KostaZx** [comment]
> It shouldn't happen, are you using qbx_medical?
 Yes.

**Comment by KostaZx** [comment]
Yes.

**Comment by KostaZx** [comment]
> It shouldn't happen, are you using qbx_medical?

any updates?

**Comment by TonybynMp4** [comment]
I'll check it out soon
