### ISSUE TITLE
Changing seat

### ISSUE THREAD

**Issue by TomTheDark** [Qbox-project/qbx_radialmenu#49]
### Summary

After enable the vehicle seat, when i open the menu and go to the vehicle part, the menu disappear

### Reproduction

Uncomment this part of the code for enable the changing seat (line 114 */client/main.lua)  : ![image](https://github.com/Qbox-project/qbx_radialmenu/assets/99438182/ccef4f60-858b-4d5a-92ac-1cf752c6909e)

Then after a restart of my server, i open the menu and go to the vehicle part and the menu desapeard, and gave me this error : 
![image](https://github.com/Qbox-project/qbx_radialmenu/assets/99438182/1d11ad35-9722-4ac8-bbb2-4e16947b2f6e)

### Expected behavior

Can have the changing seat menu

### Actual behavior

Menu disapeard

### Current Version

qbx_radialmenu 0.1.0

### Custom Resources

None

**Comment by CarlBishop** [comment]
same. it has been commented out for some reason. We miss this feature

**Comment by 0xkuze** [comment]
hey any update on this?

**Comment by frostfire575** [comment]
> hey any update on this?

use this : https://github.com/Qbox-project/qbx_radialmenu/pull/66
