### ISSUE TITLE
Double Job Menu T

### ISSUE THREAD

**Issue by icarusmods** [Qbox-project/qbx_radialmenu#50]
### Summary

Two job menus showing while on duty, one showing while off

### Reproduction

1. Go on duty for job
2. Open radial and see two job menus
3. Go off duty for job
4. See a radial that shouldnt be there

### Expected behavior

Job menu disappear while off duty, only one showing while on

### Actual behavior

Two job menus show show

### Additional context

To fix, at line 145 in qbx_radialmenu/client/main.lua add

if not onduty then return end 

looks like this
![image](https://github.com/Qbox-project/qbx_radialmenu/assets/145874981/52e30c2e-7c32-4ff4-9302-0255c0980793)
Fixed and works in my server

### Current Version

0.1.0

### Custom Resources

None interfering

**Comment by MafewTM** [comment]
Should be sorted with the new commit
